defaultRules:
  create: true
  rules:
    etcd: false
    kubeScheduler: false

alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m
    route:
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'null'
      routes:
      - match:
          alertname: Watchdog
        receiver: 'null'
    receivers:
    - name: 'null'

grafana:
  enabled: false  # We're deploying Grafana separately

prometheus:
  prometheusSpec:
    retention: 10d
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m
    additionalScrapeConfigs:
      - job_name: 'snmp'
        static_configs:
          - targets:
            - 'snmp-exporter:9116'
        metrics_path: '/snmp'
        params:
          module: [pfsense]
          target: ['pfsense.vermillion.local']
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - action: labelmap
            regex: __meta_snmp_(.+)
      - job_name: 'node'
        static_configs:
          - targets: ['node-exporter:9100']
      - job_name: 'cadvisor'
        static_configs:
          - targets: ['cadvisor:8080']

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  enabled: true

snmpExporter:
  enabled: true
  config:
    modules:
      pfsense:
        walk:
          - sysUpTime
          - ifDescr
          - ifAdminStatus
          - ifOperStatus
          - ifHCInOctets
          - ifHCOutOctets
          - ifInErrors
          - ifOutErrors
        version: 2
        auth:
          community: public
        lookups:
          - source_indexes: [ifDescr]
            lookup: ifAlias
            drop_source_indexes: true 