name: 'Documentation Check'

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  markdown-link-check:
    name: 'Check Markdown Links'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check Markdown Links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        folder-path: '.'
        config-file: '.github/workflows/mlc_config.json'

  markdown-lint:
    name: 'Markdown Lint'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run markdownlint
      uses: DavidAnson/markdownlint-cli2-action@v15
      with:
        globs: '**/*.md' 