name: 'Format and Lint'

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - '**/*.md'
      - '.markdownlint.json'
      - '.prettierrc'

jobs:
  format:
    name: 'Format Markdown'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Format with Prettier
      id: prettier
      uses: creyD/prettier_action@v4.3
      with:
        prettier_options: --write **/*.md --prose-wrap always --print-width 80
        commit_message: "style: format markdown files"
        only_changed: true

    - name: Add PR comment
      if: steps.prettier.outputs.prettier_output != ''
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.name,
            body: '✨ Markdown files have been automatically formatted for consistency.'
          }) 